#!/usr/bin/env bash
if [ ! -z $ATLANG_ROOT_DIR ]; then

    cd $ATLANG_ROOT_DIR/build
    make clean

    cd $ATLANG_ROOT_DIR
    if [ -d $ATLANG_ROOT_DIR/bin ]; then
        rm -rf $ATLANG_ROOT_DIR/bin
    fi

    if [ -d $ATLANG_ROOT_DIR/test/bin ]; then
        rm -rf $ATLANG_ROOT_DIR/test/bin
    fi

    if [ -d $ATLANG_ROOT_DIR/build ]; then
        rm -rf $ATLANG_ROOT_DIR/build
    fi
else
    echo "error: ATLANG environment not set"
fi
