#!/usr/bin/env bash
if [ $(basename $PWD) != "atlang" ]; then
    echo "This script must be run in the atlang directory"
    exit
fi

if [ -z $ATLANG_ROOT_DIR ]; then
    if [ ! -d build ]; then
        mkdir build
    fi
    export ATLANG_ROOT_DIR=$PWD
    export PATH=$ATLANG_ROOT_DIR/bin:$ATLANG_ROOT_DIR/utils:$PATH
    bash --init-file <( echo "source $HOME/.bashrc; cd $ATLANG_ROOT_DIR/build; cmake ..; PS1='(atlang) \u@\h:\w \$ '")
else
    cd $ATLANG_ROOT_DIR
    if [ ! -d build ]; then
        mkdir build
    fi
    cd build
    cmake ..
fi

